#!/bin/bash

/sbin/insmod ipv6

# enable "router" mode
echo "1" >/proc/sys/net/ipv6/conf/all/forwarding

# Set kernel ipv6 route cap to omega
echo "1024000" >/proc/sys/net/ipv6/route/max_size 2>/dev/null

